import type { WCAGCriterion } from './types';

export const wcagCriteria: WCAGCriterion[] = [
	// Principle 1: Perceivable
	{ number: '1.1.1', title: 'Non-text Content', titleEs: 'Contenido no textual', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.1', title: 'Audio-only and Video-only (Prerecorded)', titleEs: 'Solo audio y solo video (grabado)', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.2', title: 'Captions (Prerecorded)', titleEs: 'Subtítulos (grabados)', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.3', title: 'Audio Description or Media Alternative (Prerecorded)', titleEs: 'Audiodescripción o Medio Alternativo (grabado)', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.4', title: 'Captions (Live)', titleEs: 'Subtítulos (en vivo)', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.5', title: 'Audio Description (Prerecorded)', titleEs: 'Audiodescripción (grabado)', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.6', title: 'Sign Language (Prerecorded)', titleEs: 'Lengua de señas (grabado)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.7', title: 'Extended Audio Description (Prerecorded)', titleEs: 'Audiodescripción extendida (grabado)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.8', title: 'Media Alternative (Prerecorded)', titleEs: 'Medio alternativo (grabado)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.2.9', title: 'Audio-only (Live)', titleEs: 'Solo audio (en vivo)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.1', title: 'Info and Relationships', titleEs: 'Información y relaciones', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.2', title: 'Meaningful Sequence', titleEs: 'Secuencia significativa', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.3', title: 'Sensory Characteristics', titleEs: 'Características sensoriales', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.4', title: 'Orientation', titleEs: 'Orientación', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.5', title: 'Identify Input Purpose', titleEs: 'Identificar el propósito de entrada', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.3.6', title: 'Identify Purpose', titleEs: 'Identificar propósito', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.1', title: 'Use of Color', titleEs: 'Uso del color', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.2', title: 'Audio Control', titleEs: 'Control del audio', level: 'A', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.3', title: 'Contrast (Minimum)', titleEs: 'Contraste (mínimo)', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.4', title: 'Resize Text', titleEs: 'Cambio de tamaño del texto', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.5', title: 'Images of Text', titleEs: 'Imágenes de texto', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.6', title: 'Contrast (Enhanced)', titleEs: 'Contraste (mejorado)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.7', title: 'Low or No Background Audio', titleEs: 'Audio de fondo bajo o ausente', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.8', title: 'Visual Presentation', titleEs: 'Presentación visual', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.9', title: 'Images of Text (No Exception)', titleEs: 'Imágenes de texto (sin excepción)', level: 'AAA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.10', title: 'Reflow', titleEs: 'Redistribución', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.11', title: 'Non-text Contrast', titleEs: 'Contraste no textual', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.12', title: 'Text Spacing', titleEs: 'Espaciado del texto', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },
	{ number: '1.4.13', title: 'Content on Hover or Focus', titleEs: 'Contenido en hover o focus', level: 'AA', principle: 'Perceivable', principleEs: 'Perceptible' },

	// Principle 2: Operable
	{ number: '2.1.1', title: 'Keyboard', titleEs: 'Teclado', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.1.2', title: 'No Keyboard Trap', titleEs: 'Sin trampas de teclado', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.1.3', title: 'Keyboard (No Exception)', titleEs: 'Teclado (sin excepción)', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.1.4', title: 'Character Key Shortcuts', titleEs: 'Atajos de teclado de caracteres', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.1', title: 'Timing Adjustable', titleEs: 'Tiempo ajustable', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.2', title: 'Pause, Stop, Hide', titleEs: 'Pausar, detener, ocultar', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.3', title: 'No Timing', titleEs: 'Sin tiempo', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.4', title: 'Interruptions', titleEs: 'Interrupciones', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.5', title: 'Re-authenticating', titleEs: 'Reautenticación', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.2.6', title: 'Timeouts', titleEs: 'Tiempos de espera', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.3.1', title: 'Three Flashes or Below Threshold', titleEs: 'Tres destellos o bajo el umbral', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.3.2', title: 'Three Flashes', titleEs: 'Tres destellos', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.3.3', title: 'Animation from Interactions', titleEs: 'Animación desde interacciones', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.1', title: 'Bypass Blocks', titleEs: 'Saltar bloques', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.2', title: 'Page Titled', titleEs: 'Páginas tituladas', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.3', title: 'Focus Order', titleEs: 'Orden del foco', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.4', title: 'Link Purpose (In Context)', titleEs: 'Propósito del enlace (en contexto)', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.5', title: 'Multiple Ways', titleEs: 'Múltiples vías', level: 'AA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.6', title: 'Headings and Labels', titleEs: 'Encabezados y etiquetas', level: 'AA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.7', title: 'Focus Visible', titleEs: 'Foco visible', level: 'AA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.8', title: 'Location', titleEs: 'Ubicación', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.9', title: 'Link Purpose (Link Only)', titleEs: 'Propósito del enlace (solo enlace)', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.10', title: 'Section Headings', titleEs: 'Encabezados de sección', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.11', title: 'Focus Not Obscured (Minimum)', titleEs: 'Foco no oscurecido (mínimo)', level: 'AA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.12', title: 'Focus Not Obscured (Enhanced)', titleEs: 'Foco no oscurecido (mejorado)', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.4.13', title: 'Focus Appearance', titleEs: 'Apariencia del foco', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.1', title: 'Pointer Gestures', titleEs: 'Gestos del puntero', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.2', title: 'Pointer Cancellation', titleEs: 'Cancelación del puntero', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.3', title: 'Label in Name', titleEs: 'Etiqueta en el nombre', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.4', title: 'Motion Actuation', titleEs: 'Actuación por movimiento', level: 'A', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.5', title: 'Target Size (Enhanced)', titleEs: 'Tamaño del objetivo (mejorado)', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.6', title: 'Concurrent Input Mechanisms', titleEs: 'Mecanismos de entrada concurrentes', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.7', title: 'Dragging Movements', titleEs: 'Movimientos de arrastre', level: 'AAA', principle: 'Operable', principleEs: 'Operable' },
	{ number: '2.5.8', title: 'Target Size (Minimum)', titleEs: 'Tamaño del objetivo (mínimo)', level: 'AA', principle: 'Operable', principleEs: 'Operable' },

	// Principle 3: Understandable
	{ number: '3.1.1', title: 'Language of Page', titleEs: 'Idioma de la página', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.1.2', title: 'Language of Parts', titleEs: 'Idioma de las partes', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.1.3', title: 'Unusual Words', titleEs: 'Palabras inusuales', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.1.4', title: 'Abbreviations', titleEs: 'Abreviaturas', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.1.5', title: 'Reading Level', titleEs: 'Nivel de lectura', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.1.6', title: 'Pronunciation', titleEs: 'Pronunciación', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.1', title: 'On Focus', titleEs: 'Al enfocar', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.2', title: 'On Input', titleEs: 'Al ingresar', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.3', title: 'Consistent Navigation', titleEs: 'Navegación consistente', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.4', title: 'Consistent Identification', titleEs: 'Identificación consistente', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.5', title: 'Change on Request', titleEs: 'Cambio a petición', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.2.6', title: 'Consistent Help', titleEs: 'Ayuda consistente', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.1', title: 'Error Identification', titleEs: 'Identificación de errores', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.2', title: 'Labels or Instructions', titleEs: 'Etiquetas o instrucciones', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.3', title: 'Error Suggestion', titleEs: 'Sugerencia de error', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.4', title: 'Error Prevention (Legal, Financial, Data)', titleEs: 'Prevención de errores (Legal, Financiero, Datos)', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.5', title: 'Help', titleEs: 'Ayuda', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.6', title: 'Error Prevention (All)', titleEs: 'Prevención de errores (Todos)', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.7', title: 'Redundant Entry', titleEs: 'Entrada redundante', level: 'A', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.8', title: 'Accessible Authentication (Minimum)', titleEs: 'Autenticación accesible (mínimo)', level: 'AA', principle: 'Understandable', principleEs: 'Comprensible' },
	{ number: '3.3.9', title: 'Accessible Authentication (Enhanced)', titleEs: 'Autenticación accesible (mejorado)', level: 'AAA', principle: 'Understandable', principleEs: 'Comprensible' },

	// Principle 4: Robust
	{ number: '4.1.1', title: 'Parsing', titleEs: 'Procesamiento', level: 'A', principle: 'Robust', principleEs: 'Robusto' },
	{ number: '4.1.2', title: 'Name, Role, Value', titleEs: 'Nombre, Función, Valor', level: 'A', principle: 'Robust', principleEs: 'Robusto' },
	{ number: '4.1.3', title: 'Status Messages', titleEs: 'Mensajes de estado', level: 'AA', principle: 'Robust', principleEs: 'Robusto' }
];
